Run npm test -- --coverage
npm error Missing script: "test"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-05-06T19_57_44_126Z-debug-0.log
Error: Process completed with exit code 1.
